##############################################################
# apache2
##############################################################
- name: install httpd
  package:
    name:
      - "httpd"
      - "httpd-devel"
    state: latest

- name: upload reverse proxy config
  template:
    src: redmine.conf
    dest: /etc/httpd/conf.d/
    owner: root
    group: root
    mode: 0644

- name: systemctl httpd
  systemd:
    name: httpd
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: firewalld open http
  firewalld:
    service: http
    state: enabled
    permanent: true
    immediate: yes
