##############################################################
# PostgreSQL
##############################################################
- name: install repository
  package:
    name: "{{ repo_url }}"
    disable_gpg_check: yes

- name: disable postgresql
  command: "dnf -qy module disable postgresql"
  when: ansible_distribution_major_version >= "8"

- name: install epel-release
  package:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    disable_gpg_check: yes

- name: install psycopg2 ver7
  package:
    name:
      - "python-psycopg2"
      - "centos-release-scl"
    disable_gpg_check: yes
  when: ansible_distribution_major_version == "7"

- name: install psycopg2 ver8
  package:
    name:
      - "python2-psycopg2"
      - "python3-psycopg2"
    disable_gpg_check: yes
  when: ansible_distribution_major_version >= "8"

- name: install postgresql
  package:
    name:
      - "postgresql{{ postgres.pg_version }}"
      - "postgresql{{ postgres.pg_version }}-server"
      - "postgresql{{ postgres.pg_version }}-devel"
    disable_gpg_check: yes

- name: initdb
  command:
    "postgresql-{{ postgres.pg_version }}-setup initdb"
  environment:
    PATH: "{{ pg_bin_path }}:{{ ansible_env.PATH }}"
  register:
    result
  failed_when: result.rc not in [0, 1]

- name: systemctl postgresql
  systemd:
    name: postgresql-{{ postgres.pg_version }}
    state: restarted
    enabled: yes

- name: create postgresql user
  become_user: postgres
  postgresql_user:
    name: "{{ postgres.db_user }}"
    password: "{{ postgres.db_pass }}"

- name: create postgresql database
  become_user: postgres
  postgresql_db:
    name: "{{ postgres.db_name }}"
    owner: "{{ postgres.db_user }}"
    encoding: 'UTF-8'
    lc_collate: 'ja_JP.UTF-8'
    lc_ctype: 'ja_JP.UTF-8'
    template: 'template0'

